-- ============================================================
-- Recall — Postgres Schema
-- All timestamps in UTC. UUIDs generated by the application.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Workspaces ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS workspaces (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    -- Per-workspace Moss isolation (Phase 3)
    moss_project_id TEXT,
    moss_project_key TEXT,
    moss_index_name TEXT,
    allowed_domains TEXT[] DEFAULT ARRAY['wikipedia.org','github.com','docs.python.org','nodejs.org'],
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Sessions ─────────────────────────────────────────────────────
-- One session per participant (human or agent) per workspace
CREATE TABLE IF NOT EXISTS sessions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    display_name    TEXT NOT NULL,
    participant_type TEXT NOT NULL CHECK (participant_type IN ('human','agent')),
    agent_role      TEXT CHECK (agent_role IN ('planner','executor','reviewer','escalator')),
    token           TEXT NOT NULL UNIQUE,        -- issued on join
    connected_at    TIMESTAMPTZ,
    disconnected_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Tasks ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tasks (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    goal            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'planning'
                        CHECK (status IN ('planning','executing','reviewing','escalated','completed','failed')),
    -- LangGraph checkpoint thread id (matches thread_id in checkpointer)
    langgraph_thread_id TEXT UNIQUE,
    review_attempts INT NOT NULL DEFAULT 0,
    subtasks        JSONB DEFAULT '[]',
    result          JSONB,
    error           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Messages ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    task_id         UUID REFERENCES tasks(id) ON DELETE SET NULL,
    session_id      UUID REFERENCES sessions(id) ON DELETE SET NULL,
    role            TEXT NOT NULL CHECK (role IN ('human','planner','executor','reviewer','system')),
    content         TEXT NOT NULL,
    metadata        JSONB DEFAULT '{}',
    -- Moss sync status
    moss_indexed    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Audit Logs ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID REFERENCES workspaces(id) ON DELETE SET NULL,
    task_id         UUID REFERENCES tasks(id) ON DELETE SET NULL,
    session_id      UUID REFERENCES sessions(id) ON DELETE SET NULL,
    event_type      TEXT NOT NULL,   -- e.g. 'domain_blocked', 'task_escalated', 'agent_retry'
    severity        TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warn','error','critical')),
    payload         JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_sessions_workspace ON sessions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_tasks_workspace ON tasks(workspace_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_messages_workspace ON messages(workspace_id);
CREATE INDEX IF NOT EXISTS idx_messages_task ON messages(task_id);
CREATE INDEX IF NOT EXISTS idx_messages_moss ON messages(moss_indexed) WHERE moss_indexed = FALSE;
CREATE INDEX IF NOT EXISTS idx_audit_workspace ON audit_logs(workspace_id);
CREATE INDEX IF NOT EXISTS idx_audit_event ON audit_logs(event_type);

-- ── updated_at trigger ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_workspaces_updated_at
    BEFORE UPDATE ON workspaces
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
